#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 100 with fizz buzz

count=1

while [ $count -lt 101 ]
do
	if [ $((count % 3)) -eq 0 ] && [ $((count % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((count % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((count % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$count"
	fi
	((count++))
done
