#!/usr/bin/env bash
#replaces some host addresses with new ones
cp /etc/hosts ~/hosts.new
sed -i s/^127\.0\.0\.2.*$// ~/hosts.new
sed -i s/^127\.0\.0\.1.*$// ~/hosts.new
sed -i s/^8\.8\.8\.8.*$// ~/hosts.new
sed -i s/^.*localhost.*$// ~/hosts.new
sed -i '1 i  127\.0\.0\.2	localhost' ~/hosts.new
sed -i '1 i 8\.8\.8\.8	facebook\.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts

